apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team1-multi-stage-apps
  namespace: team1-apps
spec:
  destination:
    namespace: team1-apps
    server: https://kubernetes.default.svc
  project: team1-project
  source:
    repoURL: https://github.com/suxess-it/sx-cnp-oss
    targetRevision: main
    path: team-apps/onboarding-apps-charts/multi-stage-app-with-kargo-pipeline
    helm:
      values: |
        teamName: team1
        appName: multi-stage-app
        repoUrl: https://github.com/suxess-it/sx-cnp-oss-demo-app
        createAppNamespace: true
        stages:
          - name: "test"
            subscriptions: 
              warehouse: "warehouse-{{ .Values.appName }}"
          - name: "qa"
            subscriptions: 
              upstreamStages:
              - name: test
          - name: "prod"
            subscriptions: 
              upstreamStages:
              - name: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
